Repository jjoohee95/NBC_iOS_4Team, pull requests merged in 2024-07, with the labels that each got.

#12 Art/#1 login view UI
  MovieReservation_4Team.xcodeproj/project.pbxproj
  MovieReservation_4Team.xcodeproj/project.xcworkspace/xcuserdata/ijingyu.xcuserdatad/UserInterfaceState.xcuserstate
  MovieReservation_4Team.xcodeproj/xcuserdata/ijingyu.xcuserdatad/xcschemes/xcschememanagement.plist
  MovieReservation_4Team/View/LoginView.swift
  MovieReservation_4Team/View/MainView.swift
  MovieReservation_4Team/View/SignUpVIew.swift
  MovieReservation_4Team/View/logo.xcassets/Contents.json
  MovieReservation_4Team/View/logo.xcassets/nigabox.imageset/Contents.json
  MovieReservation_4Team/View/logo.xcassets/nigabox.imageset/LOGO.png
Labels: 이진규, ART

#25 Art/#9 bookmark view
  MovieReservation_4Team.xcodeproj/project.pbxproj
  MovieReservation_4Team.xcodeproj/project.xcworkspace/xcuserdata/t2023-m0023.xcuserdatad/UserInterfaceState.xcuserstate
  MovieReservation_4Team.xcodeproj/xcuserdata/t2023-m0023.xcuserdatad/xcschemes/xcschememanagement.plist
  MovieReservation_4Team/Assets.xcassets/heartimage.imageset/Contents.json
  MovieReservation_4Team/Assets.xcassets/heartimage.imageset/heartimage.png
  MovieReservation_4Team/Controller/BookmarkController.swift
  MovieReservation_4Team/Controller/favoritesViewController.swift
  MovieReservation_4Team/View/BookmarkView.swift
  MovieReservation_4Team/View/BookmarkViewCell.swift
  MovieReservation_4Team/View/CustomNavigationBarView.swift
  MovieReservation_4Team/View/favoritesView.swift
  MovieReservation_4Team/View/favoritesViewCell.swift
Labels: 이주희, ART

#42 Etc/#39 UI fix
  MovieReservation_4Team.xcodeproj/project.pbxproj
  MovieReservation_4Team/Controller/SearchController.swift
  MovieReservation_4Team/Controller/TabBarController.swift
  MovieReservation_4Team/View/ReservaitionView.swift
  MovieReservation_4Team/View/SearchView.swift
Labels: 이주희, ART, ETC
